//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class example {
  public static double my_variable {
    set {
      examplePINVOKE.my_variable_set(value);
    } 
    get {
      double ret = examplePINVOKE.my_variable_get();
      return ret;
    } 
  }

  public static int fact(int n) {
    int ret = examplePINVOKE.fact(n);
    return ret;
  }

  public static int my_mod(int x, int y) {
    int ret = examplePINVOKE.my_mod(x, y);
    return ret;
  }

  public static string get_time() {
    string ret = examplePINVOKE.get_time();
    return ret;
  }

}
